-- TEST EACH PROCEDURE TO SEE IF THEY WORK. 
-- AS EACH PROCEDURE CHECKS OUT / RUN WHOLE LINE OF SQL CODE TO SEE IF ITS SUCCESSFUL.
-- IF SUCCESSFUL - READY FOR DEMO WITH KAREN.

USE SEM2DB;

IF OBJECT_ID('Sale') IS NOT NULL
DROP TABLE SALE;

IF OBJECT_ID('Product') IS NOT NULL
DROP TABLE PRODUCT;

IF OBJECT_ID('Customer') IS NOT NULL
DROP TABLE CUSTOMER;

IF OBJECT_ID('Location') IS NOT NULL
DROP TABLE LOCATION;

GO

CREATE TABLE CUSTOMER (
CUSTID	INT
, CUSTNAME	NVARCHAR(100)
, SALES_YTD	MONEY
, STATUS	NVARCHAR(7)
, PRIMARY KEY	(CUSTID) 
);


CREATE TABLE PRODUCT (
PRODID	INT
, PRODNAME	NVARCHAR(100)
, SELLING_PRICE	MONEY
, SALES_YTD	MONEY
, PRIMARY KEY	(PRODID)
);

CREATE TABLE SALE (
SALEID	BIGINT
, CUSTID	INT
, PRODID	INT
, QTY	INT
, PRICE	MONEY
, SALEDATE	DATE
, PRIMARY KEY 	(SALEID)
, FOREIGN KEY 	(CUSTID) REFERENCES CUSTOMER
, FOREIGN KEY 	(PRODID) REFERENCES PRODUCT
);

CREATE TABLE LOCATION (
  LOCID	NVARCHAR(5)
, MINQTY	INTEGER
, MAXQTY	INTEGER
, PRIMARY KEY 	(LOCID)
, CONSTRAINT CHECK_LOCID_LENGTH CHECK (LEN(LOCID) = 5)
, CONSTRAINT CHECK_MINQTY_RANGE CHECK (MINQTY BETWEEN 0 AND 999)
, CONSTRAINT CHECK_MAXQTY_RANGE CHECK (MAXQTY BETWEEN 0 AND 999)
, CONSTRAINT CHECK_MAXQTY_GREATER_MIXQTY CHECK (MAXQTY >= MINQTY)
);

IF OBJECT_ID('SALE_SEQ') IS NOT NULL
DROP SEQUENCE SALE_SEQ;
CREATE SEQUENCE SALE_SEQ;

GO

--STORE PROCEDURE #1 ADD_CUSTOMER 
IF OBJECT_ID('ADD_CUSTOMER') IS NOT NULL
DROP PROCEDURE ADD_CUSTOMER;
GO

CREATE PROCEDURE ADD_CUSTOMER @PCUSTID INT, @PCUSTNAME NVARCHAR(100) AS

BEGIN
    BEGIN TRY

        IF @PCUSTID < 1 OR @PCUSTID > 499
            THROW 50020, 'Customer ID out of range', 1

        INSERT INTO CUSTOMER (CUSTID, CUSTNAME, SALES_YTD, STATUS) 
        VALUES (@PCUSTID, @PCUSTNAME, 0, 'OK');

    END TRY
    BEGIN CATCH
        if ERROR_NUMBER() = 2627
            THROW 50010, 'Duplicate customer ID', 1
        ELSE IF ERROR_NUMBER() = 50020
            THROW
        ELSE
            BEGIN
                DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
                THROW 50000, @ERRORMESSAGE, 1
            END; 
    END CATCH;

END;
GO

-- TESTING BY ADDING CUSTOMERS INTO CUSTOMER TABLE
EXECUTE ADD_CUSTOMER @pcustid = 1, @pcustname = 'Dummy One';
EXECUTE ADD_CUSTOMER @pcustid = 200, @pcustname = 'Dummy Two';
EXECUTE ADD_CUSTOMER @pcustid = 499, @pcustname = 'Dummy Three';
SELECT * FROM CUSTOMER;

--STORE PROCEDURE #2 DELETE_ALL_CUSTOMERS
IF OBJECT_ID('DELETE_ALL_CUSTOMERS') IS NOT NULL
DROP PROCEDURE DELETE_ALL_CUSTOMERS;
GO

CREATE PROCEDURE DELETE_ALL_CUSTOMERS AS
BEGIN
    BEGIN TRY
        DELETE FROM CUSTOMER;
        RETURN @@ROWCOUNT;
    END TRY
    BEGIN CATCH
        DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
        THROW 50000, @ERRORMESSAGE, 1
    END CATCH;
END;
GO

-- TESTING BY DELETING CUSTOMERS FROM CUSTOMER TABLE.
EXECUTE DELETE_ALL_CUSTOMERS; 
SELECT * FROM CUSTOMER; 
GO


--STORE PROCEDURE #3 ADD_PRODUCT 
IF OBJECT_ID('ADD_PRODUCT') IS NOT NULL 
DROP PROCEDURE ADD_PRODUCT; 
GO 

CREATE PROCEDURE ADD_PRODUCT @PRODID INT, @PRODNAME NVARCHAR(100), @PPRICE MONEY AS
BEGIN
    BEGIN TRY

        IF @PRODID < 1000 OR @PRODID > 2500
            THROW 50040, 'Product ID out of range', 1
        
        IF @PPRICE < 0 OR @PPRICE > 999.99
            THROW 50050, 'Price out of range', 1

        INSERT INTO PRODUCT (PRODID, PRODNAME, SELLING_PRICE, SALES_YTD) 
        VALUES (@PRODID, @PRODNAME, @PPRICE, 0);

    END TRY
    BEGIN CATCH
        IF ERROR_NUMBER() = 2627 -- cannot insert duplicate key in object 
            THROW 50030, 'Duplicate product ID', 1
        ELSE IF ERROR_NUMBER() = 50040
            THROW
        ELSE IF ERROR_NUMBER() = 50050
            THROW
        ELSE
            BEGIN
                DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
                THROW 50000, @ERRORMESSAGE, 1
            END; 
    END CATCH;
END;
GO


-- TESTING: Adding Products into the Product Table
EXECUTE ADD_PRODUCT @PRODID = 100, @PRODNAME ='Little', @PPRICE = 500 --prod id out of range
EXECUTE ADD_PRODUCT @PRODID = 1800, @PRODNAME ='Big', @PPRICE = 10000 --price exceeds range 
EXECUTE ADD_PRODUCT @PRODID = 2001, @PRODNAME ='Perfect', @PPRICE = 100 --suits parameters
EXECUTE ADD_PRODUCT @PRODID = 2001, @PRODNAME ='Copy', @PPRICE = 100 --duplicate prodid
SELECT * FROM PRODUCT
GO


-- STORE PROCEDURE #4 DELETE_ALL_PRODUCTS 
IF OBJECT_ID('DELETE_ALL_PRODUCTS') IS NOT NULL
DROP PROCEDURE DELETE_ALL_PRODUCTS;
GO

CREATE PROCEDURE DELETE_ALL_PRODUCTS AS
BEGIN
    BEGIN TRY
        DELETE FROM PRODUCT;
        RETURN @@ROWCOUNT;
    END TRY
    BEGIN CATCH
        DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
        THROW 50000, @ERRORMESSAGE, 1
    END CATCH;
END;
GO
-- TESTING: Deleting Products from Table 
EXECUTE DELETE_ALL_PRODUCTS;

--STORE PROCEDURE #5 
IF OBJECT_ID('GET_CUSTOMER_STRING') IS NOT NULL 
DROP PROCEDURE GET_CUSTOMER_STRING 
GO 

CREATE PROCEDURE GET_CUSTOMER_STRING @PCUSTID INT, @pReturnString NVARCHAR(100) OUTPUT AS
BEGIN
    DECLARE @PCUSTNAME NVARCHAR(100), @STATUS NVARCHAR(7), @SALESYTD MONEY;

    BEGIN TRY
    SELECT @PCUSTNAME = CUSTNAME, @STATUS = [STATUS], @SALESYTD = SALES_YTD
    FROM CUSTOMER 
    WHERE CUSTID = @PCUSTID

    SET @pReturnString = CONCAT('CustId:', @PCUSTID, 'Name: ', @PCUSTNAME, 'Status: ', @STATUS, 'SalesYTD: ', @SALESYTD);

    END TRY
    BEGIN CATCH
        IF ERROR_NUMBER() = 50060 
            THROW
        ELSE
            BEGIN
                DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
                THROW 50000, @ERRORMESSAGE, 1
            END; 
    END CATCH;
END;
-- TESTING: Testing Customer String
BEGIN
    DECLARE @OUTPUTVALUE NVARCHAR(MAX);
    EXECUTE GET_CUSTOMER_STRING @pcustid= 1, @preturnstring = @OUTPUTVALUE OUTPUT;
    PRINT (@OUTPUTVALUE);
END


--STORE PROCEDURE #6 UPDATE CUSTOMER SALES
IF OBJECT_ID('UPD_CUST_SALESYTD') IS NOT NULL 
DROP PROCEDURE UPD_CUST_SALESYTD;
GO

CREATE PROCEDURE UPD_CUST_SALESYTD @PCUSTID INT, @PAMT MONEY AS 
BEGIN
    BEGIN TRY
        IF @PAMT < -999.99 or @pAMT > 999.99 
        THROW 50080, 'Amount out of range', 1 

        UPDATE CUSTOMER 
        SET SALES_YTD = (SALES_YTD + @pAMT)
        WHERE @pCUSTID = CUSTID;  
    END TRY
    BEGIN CATCH 
        IF ERROR_NUMBER() = 2627
        THROW 50070, 'Customer ID not found', 1 
        ELSE 
            BEGIN 
                DECLARE @ERRORMESSAGE NVARCHAR (100) = ERROR_MESSAGE(); 
                THROW 50000, @ERRORMESSAGE, 1
            END
    END CATCH 
END; 

-- TESTING: Updating sales price in customer table.
DELETE FROM CUSTOMER
EXECUTE ADD_CUSTOMER @PCUSTID = 1, @PCUSTNAME = 'Dummy Four';
SELECT * FROM CUSTOMER

EXECUTE UPD_CUST_SALESYTD @pcustid = 1, @pamt = 100; 
EXECUTE UPD_CUST_SALESYTD @pcustid = 1, @pamt = 500; 
EXECUTE UPD_CUST_SALESYTD @pcustid = 1, @pamt = -1000; 
EXECUTE UPD_CUST_SALESYTD @pcustid = 1, @pamt = 1000; 
SELECT * FROM CUSTOMER


--STORE PROCEDURE #7 GET PRODUCT STRING
IF OBJECT_ID('GET_PROD_STRING') IS NOT NULL
DROP PROCEDURE GET_PROD_STRING;
GO

CREATE PROCEDURE GET_PROD_STRING @PRODID INT, @pReturnString NVARCHAR(1000) OUTPUT AS
BEGIN
    DECLARE @PRODNAME NVARCHAR(100), @PRICE MONEY, @SALESYTD MONEY;

    BEGIN TRY
    SELECT @PRODNAME = PRODNAME, @PRICE = SELLING_PRICE, @SALESYTD = SALES_YTD
    FROM PRODUCT 
    WHERE PRODID = @PRODID

    IF @@ROWCOUNT = 0
    THROW 50090, 'Product ID not found', 1

    SET @pReturnString = CONCAT('Prodid: ', @PRODID, 'Name: ', @PRODNAME, 'Price: ', @PRICE, 'SalesYTD: ', @SALESYTD);

    END TRY
    BEGIN CATCH
        IF ERROR_NUMBER() = 50090
            THROW
        ELSE
            BEGIN
                DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
                THROW 50000, @ERRORMESSAGE, 1
            END; 
    END CATCH;
END;
GO

--TESTING: Get product string. 
SELECT * FROM PRODUCT
BEGIN
    DECLARE @OUTPUTVALUE NVARCHAR(100);
    EXECUTE GET_PROD_STRING @prodid = 2001, @preturnstring = @OUTPUTVALUE OUTPUT;
    PRINT (@OUTPUTVALUE);
END
GO


--STORED PROCEDURE #8
IF OBJECT_ID('UPD_PROD_SALESYTD') IS NOT NULL
DROP PROCEDURE UPD_PROD_SALESYTD
GO

CREATE PROCEDURE UPD_PROD_SALESYTD @PRODID INT, @PAMT MONEY AS 
BEGIN
    BEGIN TRY
    IF @pamt < -999.99 OR @pamt > 999.99
            THROW 50110, 'Amount out of range', 1
        
        UPDATE PRODUCT 
        SET SALES_YTD = SALES_YTD + @PAMT
        WHERE PRODID = @PRODID
    END TRY

    BEGIN CATCH
        if ERROR_NUMBER() = 50110
            THROW 
        if ERROR_NUMBER() = 50100
            THROW
        ELSE
            BEGIN
                DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
                THROW 50000, @ERRORMESSAGE, 1
            END;
    END CATCH
END;
GO

--TESTING: Updating product sales price. 
EXECUTE DELETE_ALL_PRODUCTS;
EXECUTE ADD_PRODUCT @prodid = 2021, @prodname = 'Dummy Five', @pprice = 100;
EXECUTE ADD_PRODUCT @prodid = 2022, @prodname = 'Dummy Six', @pprice = 200;
SELECT * FROM PRODUCT

EXECUTE UPD_PROD_SALESYTD @prodid = 2021, @pamt = 800;
EXECUTE UPD_PROD_SALESYTD @prodid = 2021, @pamt = 200;
EXECUTE UPD_PROD_SALESYTD @prodid = 2021, @pamt = -1000; 
EXECUTE UPD_PROD_SALESYTD @prodid = 2022, @pamt = 1000;
SELECT * FROM PRODUCT



-- STORED PROCEDURE #9 UPDATING CUSTOMER STATUS 
IF OBJECT_ID('UPD_CUSTOMER_STATUS') IS NOT NULL 
DROP PROCEDURE UPD_CUSTOMER_STATUS;  
GO 

CREATE PROCEDURE UPD_CUSTOMER_STATUS @PCUSTID INT, @PSTATUS NVARCHAR(100) AS  
    BEGIN 
        BEGIN TRY 
            if @@ROWCOUNT = 0 
                THROW 50120, 'Customer ID Not Found', 1 

            if @PSTATUS = 'OK' or @PSTATUS = 'SUSPEND' 
            UPDATE CUSTOMER SET STATUS = @PSTATUS 
            WHERE CUSTID = @PCUSTID 
            UPDATE CUSTOMER SET STATUS = @PSTATUS 
            WHERE CUSTID = @PCUSTID;
        END TRY 
    BEGIN CATCH 
        DECLARE @ERRORMESSAGE NVARCHAR(100) = ERROR_MESSAGE(); 
        THROW 50000, @ERRORMESSAGE, 1 
    END CATCH 
END; 
GO
-- TESTING: Updating Customer Status
EXECUTE DELETE_ALL_CUSTOMERS;
EXECUTE ADD_CUSTOMER @PCUSTID = 1, @PCUSTNAME = 'Dummy Seven';
EXECUTE ADD_CUSTOMER @PCUSTID = 2, @PCUSTNAME = 'Dummy Eight';
SELECT * FROM CUSTOMER;

EXECUTE UPD_CUSTOMER_STATUS @PCUSTID = 1, @PSTATUS = 'SUSPEND'; 
EXECUTE UPD_CUSTOMER_STATUS @PCUSTID = 2, @PSTATUS = 'SUSPEND';
SELECT * FROM CUSTOMER;

-- STORED PROCEDURE #10 
IF OBJECT_ID('ADD_SIMPLE_SALE') IS NOT NULL
DROP PROCEDURE ADD_SIMPLE_SALE;
GO

CREATE PROCEDURE ADD_SIMPLE_SALE @PCUSTID INT, @PPRODID INT, @PQTY INT AS
BEGIN
    BEGIN TRY

    DECLARE @CUSTSTATUS NVARCHAR(7);

    SELECT @CUSTSTATUS = STATUS
    FROM CUSTOMER
    WHERE CUSTID = @PCUSTID
    IF @@ROWCOUNT = 0
        THROW 50160, 'Customer ID not found', 1

    IF (@CUSTSTATUS NOT IN ('OK'))
        THROW 50150, 'Customer status is not OK', 1

    IF @PQTY<1 OR @PQTY>999
        THROW 50140, 'Sale Quantity outside valid range', 1

    DECLARE @PRODSELLPRICE MONEY;
    SELECT @PRODSELLPRICE = SELLING_PRICE
    FROM PRODUCT
    WHERE PRODID = @PPRODID
    IF @@ROWCOUNT = 0
        THROW 50170, 'Product ID not found', 1

    DECLARE @UPDATEAMT MONEY
    SET @UPDATEAMT = @PRODSELLPRICE*@PQTY;

    EXEC UPD_CUST_SALESYTD @PCUSTID = @PCUSTID, @PAMT = @UPDATEAMT
    EXEC UPD_PROD_SALESYTD @PRODID = @PPRODID, @PAMT = @UPDATEAMT

    END TRY
    BEGIN CATCH
        if ERROR_NUMBER() in (50150, 50160, 50140, 50170)
            THROW
        ELSE
            BEGIN
                DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
                THROW 50000, @ERRORMESSAGE, 1
            END; 
    END CATCH;
END;
GO

---- testing ----
DELETE FROM SALE
DELETE FROM PRODUCT
EXECUTE ADD_PRODUCT @PRODID = 2001, @PRODNAME ='Perfect', @PPRICE = 10
SELECT * FROM PRODUCT

DELETE FROM CUSTOMER
EXECUTE ADD_CUSTOMER @pcustid = 1, @pcustname = 'Dummy Nine';
EXECUTE ADD_CUSTOMER @pcustid = 2, @pcustname = 'Dummy Ten';
EXECUTE UPD_CUSTOMER_STATUS @pcustid = 2, @pstatus = 'SUSPEND';
SELECT * FROM CUSTOMER

EXECUTE ADD_SIMPLE_SALE @pcustid = 1, @pprodid = 2001, @pqty = 10;
SELECT * FROM PRODUCT
SELECT * FROM CUSTOMER
SELECT * FROM SALE


--STORED PROCEDURE #11
IF OBJECT_ID('SUM_CUSTOMER_SALESYTD') IS NOT NULL
DROP PROCEDURE SUM_CUSTOMER_SALESYTD;
GO

CREATE PROCEDURE SUM_CUSTOMER_SALESYTD AS
BEGIN
    BEGIN TRY

    SELECT SUM(SALES_YTD)
    FROM CUSTOMER

    END TRY
    BEGIN CATCH
        DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
        THROW 50000, @ERRORMESSAGE, 1
    END CATCH;
END;

GO
-- TESTING:
DELETE FROM SALE
DELETE FROM PRODUCT
EXECUTE ADD_PRODUCT @PRODID = 2001, @PRODNAME ='Perfect', @PPRICE = 10
SELECT * FROM PRODUCT

EXECUTE ADD_CUSTOMER @pcustid = 1, @pcustname = 'Dummy Eleven';
EXECUTE ADD_CUSTOMER @pcustid = 2, @pcustname = 'Dummy Twelve';
EXECUTE ADD_CUSTOMER @pcustid = 3, @pcustname = 'Dummy Thirteen';
SELECT * FROM CUSTOMER

EXECUTE SUM_CUSTOMER_SALESYTD

--STORED PROCEDURE #12
IF OBJECT_ID('SUM_PRODUCT_SALESYTD') IS NOT NULL
DROP PROCEDURE SUM_PRODUCT_SALESYTD;
GO

CREATE PROCEDURE SUM_PRODUCT_SALESYTD AS
BEGIN
    BEGIN TRY

    SELECT SUM(SALES_YTD)
    FROM PRODUCT

    END TRY
    BEGIN CATCH
        DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
        THROW 50000, @ERRORMESSAGE, 1
    END CATCH;
END;
GO

SELECT * FROM PRODUCT
EXECUTE DELETE_ALL_PRODUCTS
EXECUTE ADD_PRODUCT @PRODID = 2001, @PRODNAME = 'Perfect', @PPRICE = 10
EXECUTE ADD_PRODUCT @PRODID = 2001, @PRODNAME = 'Perfect', @PPRICE = 10

EXECUTE SUM_PRODUCT_SALESYTD

--STORED PROCEDURE #13
IF OBJECT_ID('GET_ALL_CUSTOMERS') IS NOT NULL
DROP PROCEDURE GET_ALL_CUSTOMERS;
GO
CREATE PROCEDURE GET_ALL_CUSTOMERS @POUTCUR CURSOR VARYING OUTPUT AS
BEGIN
    BEGIN TRY 
    SET NOCOUNT ON;
    SET @POUTCUR = CURSOR FOR 
    SELECT * FROM CUSTOMER;
    OPEN @POUTCUR
    END TRY
    BEGIN CATCH
        DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
        THROW 50000, @ERRORMESSAGE, 1
    END CATCH
END;
GO

-- STORED PROCEDURE #14
IF OBJECT_ID('GET_ALL_PRODUCTS') IS NOT NULL
DROP PROCEDURE GET_ALL_PRODUCTS;
GO
CREATE PROCEDURE GET_ALL_PRODUCTS @POUTCUR CURSOR VARYING OUTPUT AS
BEGIN
    BEGIN TRY 
    SET NOCOUNT ON;
    SET @POUTCUR = CURSOR FOR 
    SELECT * FROM PRODUCT;
    OPEN @POUTCUR
    END TRY
    BEGIN CATCH
    DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
    THROW 50000, @ERRORMESSAGE, 1
    END CATCH
END;

GO

--STORED PROCEDURE #15
IF OBJECT_ID('ADD_LOCATION') IS NOT NULL
DROP PROCEDURE ADD_LOCATION;
GO
CREATE PROCEDURE ADD_LOCATION @ploccode NVARCHAR(5), @pminqty INT, @pMaxQty INT AS
BEGIN
BEGIN TRY
    IF @pLocCode != 5
        THROW 50190, 'Location Code length invalid', 1
    IF @pMinQty > 999 OR @pMinQty < 0 
        THROW 50200, 'Minimum Qty out of range', 1
    IF @pMaxQty > 999 OR @pMaxQty < 0 
        THROW 50210, 'Maximum Qty out of range', 1
    IF @pMaxQty < @pMinQty 
        THROW 50220, 'Minimum Qty larger than Maximum Qty', 1
        
    INSERT INTO LOCATION (LOCID, MINQTY, MAXQTY)
    VALUES(@pLocCode, @pMinQty, @pMaxQty);
    END TRY

BEGIN CATCH
        IF ERROR_NUMBER() = 50190 OR ERROR_NUMBER() = 50200 OR ERROR_NUMBER() = 50210 OR ERROR_NUMBER() = 50220
        THROW
        IF ERROR_NUMBER() = 2627
        THROW 50180, 'Duplicate location ID',1
        ELSE
        BEGIN
            DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
            THROW 50000, @ERRORMESSAGE, 1
            END;
    END CATCH
END;
GO

-- STORED PROCEDURE #16
IF OBJECT_ID('ADD_COMPLEX_SALE') IS NOT NULL
DROP PROCEDURE ADD_COMPLEX_SALE;
GO
CREATE PROCEDURE ADD_COMPLEX_SALE @pcustid INT, @pprodid INT, @pQty INT, @pdate DATE AS
BEGIN
    BEGIN TRY 
    DECLARE @Status AS NVARCHAR(7)
    SELECT @Status = Status FROM CUSTOMER WHERE CUSTID = @pcustid
    IF @Status != 'OK'
        THROW 50240, 'Customer Status is not OK',1;
    IF @pQty > 999 or @pQty < 1
        THROW 50230, 'Sale Quantity Outside Valid Range',1;
        
    IF EXISTS (SELECT * FROM CUSTOMER WHERE CUSTID = @pcustid)
    IF EXISTS (SELECT * FROM PRODUCT WHERE PRODID = @pprodid)
        BEGIN
        DECLARE @Price AS MONEY
        SELECT @Price =  SELLING_Price FROM PRODUCT WHERE PRODID = @pprodid;
        DECLARE @total money = @pQty * @Price;
        UPDATE CUSTOMER SET SALES_YTD += @total WHERE CUSTID = @pcustid;
        UPDATE PRODUCT SET SALES_YTD += @total WHERE PRODID = @pprodid;
        DECLARE @saleid BIGINT;
        SELECT @Price = SELLING_Price FROM PRODUCT WHERE PRODID = @pprodid;
        INSERT INTO SALE (SALEID, CUSTID, PRODID, QTY, Price, SALEDATE)
        VALUES(NEXT VALUE FOR SALE_SEQ,@pcustid, @pprodid,@pQty, @Price, @pdate )
        END;
        ELSE 
            THROW 50270, 'Product ID not found',1;
        ELSE 
            THROW 50260, 'Customer ID not found',1;
    END TRY
    BEGIN CATCH
        IF ERROR_NUMBER() = 50230 OR ERROR_NUMBER() = 50240 OR ERROR_NUMBER() = 50250 OR ERROR_NUMBER() = 50260 OR ERROR_NUMBER() = 50270
        Throw
        ELSE
            BEGIN
            DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
            THROW 50000, @ERRORMESSAGE, 1
            END;
    END CATCH
END;
GO

--STORED PROCEDURE #17
IF OBJECT_ID('GET_ALL_SALES') IS NOT NULL
    DROP PROCEDURE GET_ALL_SALES
GO
CREATE PROCEDURE GET_ALL_SALES @POUTCUR CURSOR VARYING OUTPUT AS
BEGIN
    BEGIN TRY
        SET @POUTCUR = CURSOR
        FORWARD_ONLY STATIC FOR
        SELECT * FROM SALE
        OPEN @POUTCUR
    END TRY
    BEGIN CATCH
        DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
        THROW 50000, @ERRORMESSAGE, 1
    END CATCH
END

--STORED PROCEDURE #18
IF OBJECT_ID('COUNT_PRODUCT_SALES') IS NOT NULL
    DROP PROCEDURE COUNT_PRODUCT_SALES
GO
CREATE PROCEDURE COUNT_PRODUCT_SALES @pdays INT AS
BEGIN
    DECLARE @numSales INT
    BEGIN TRY
        SELECT @numSales = COUNT(*)
        FROM SALE
        WHERE DATEDIFF(day, SALEDATE, GETDATE()) BETWEEN 0 AND @pdays
    END TRY
    BEGIN CATCH
        DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
        THROW 50000, @ERRORMESSAGE, 1
    END CATCH
    RETURN @numSales
END

--STORED PROCEDURE #19
IF OBJECT_ID('DELETE_SALE') IS NOT NULL
    DROP PROCEDURE DELETE_SALE
GO
CREATE PROCEDURE DELETE_SALE @saleid BIGINT OUTPUT AS
BEGIN
DECLARE @custid INT, @prodid INT, @price INT, @qty INT, @amt INT
BEGIN TRY
    SELECT @saleid = SALEID, @custid = CUSTID, @prodid = PRODID, @price = PRICE, @qty = QTY
    FROM SALE
    WHERE SALEID = (SELECT MIN(SALEID) FROM SALE)
    IF @@ROWCOUNT = 0
        THROW 50280, 'No Sale Rows Found', 1;
    SET @amt = -1 * (@price * @qty)
    EXEC UPD_CUST_SALESYTD @pcustid = @custid, @pamt = @amt
    EXEC UPD_PROD_SALESYTD @pprodid = @prodid, @pamt = @amt
    DELETE FROM SALE
    WHERE SALEID = (SELECT MIN(SALEID) FROM SALE)
    IF @@ROWCOUNT = 0
        THROW 50280, 'No Sale Rows Found', 1;
    END TRY
    BEGIN CATCH
    IF ERROR_NUMBER() = 50280
        THROW
    ELSE
        DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
    THROW 50000, @ERRORMESSAGE, 1
    END CATCH
END
GO

--STORED PROCEDURE #20
IF OBJECT_ID('DELETE_ALL_SALES') IS NOT NULL
    DROP PROCEDURE DELETE_ALL_SALES
GO
CREATE PROCEDURE DELETE_ALL_SALES  AS
BEGIN
BEGIN TRY
    DELETE FROM SALE
    UPDATE CUSTOMER
    SET SALES_YTD = 0;
    UPDATE PRODUCT
    SET SALES_YTD = 0;
    END TRY
   
    BEGIN CATCH
    
    DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
    THROW 50000, @ERRORMESSAGE, 1
    
    END CATCH
END

--STORED PROCEDURE #21
IF OBJECT_ID('DELETE_CUSTOMER') IS NOT NULL
    DROP PROCEDURE DELETE_CUSTOMER
GO
CREATE PROCEDURE DELETE_CUSTOMER @pcustid INT AS
BEGIN
    
BEGIN TRY
    IF NOT EXISTS(SELECT * FROM CUSTOMER WHERE CUSTID = @pcustid)
        THROW 50290, 'Customer ID not found', 1
    IF EXISTS(SELECT * FROM SALE WHERE CUSTID = @pcustid)
        THROW 50300, 'Customer cannot be deleted as sales exist', 1
    DELETE FROM CUSTOMER WHERE CUSTID = @pcustid
    
    END TRY
    
    BEGIN CATCH
    IF ERROR_NUMBER() IN (50290, 50300)
        THROW
    ELSE
        DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
        THROW 50000, @ERRORMESSAGE, 1
    END CATCH
END
GO

--STORED PROCEDURE #22
IF OBJECT_ID('DELETE_PRODUCT') IS NOT NULL
DROP PROCEDURE DELETE_PRODUCT
GO
CREATE PROCEDURE DELETE_PRODUCT @pprodid INT AS
BEGIN
    BEGIN TRY
    IF NOT EXISTS(SELECT * FROM PRODUCT WHERE PRODID = @pprodid)
        THROW 50310, 'Product ID not found', 1
    IF EXISTS(SELECT * FROM SALE WHERE PRODID = @pprodid)
        THROW 50320, 'Product cannot be deleted as sales exist', 1
    DELETE FROM PRODUCT WHERE PRODID = @pprodid
    END TRY
   
    BEGIN CATCH
        IF ERROR_NUMBER() IN (50290, 50300)
            THROW
        ELSE
            DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
            THROW 50000, @ERRORMESSAGE, 1
    END CATCH
END


